# Generated by Django 3.1.5 on 2021-01-26 15:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPP', models.IntegerField(default=10, verbose_name='Номер ПП')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('nickName', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Ник')),
                ('photo', models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Фото)')),
                ('pageHeader', models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Изображение для шапки страницы')),
                ('nickNameSlug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('linkVK', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на VK')),
                ('linkTW', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Twitch')),
                ('linkYT', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube')),
                ('linkIN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров профиля')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('streaming', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Что стримит')),
                ('isAtHome', models.BooleanField(default=False, verbose_name='Отображать на главной?')),
                ('uniqUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хеш для ссылки (/star/stats/)')),
            ],
            options={
                'verbose_name': 'Стример',
                'verbose_name_plural': 'Стримеры',
            },
        ),
    ]
