# Generated by Django 3.1.12 on 2021-08-04 00:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='PlaceTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second')], verbose_name='День')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Окончание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.place', verbose_name='Место')),
                ('streamers', models.ManyToManyField(to='api.Streamer', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Строка расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
