# Generated by Django 3.1.12 on 2022-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modultxn',
            name='auth_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auth code'),
        ),
        migrations.AlterField(
            model_name='modultxn',
            name='auth_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Auth number'),
        ),
        migrations.AlterField(
            model_name='modultxn',
            name='rrn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='RRN'),
        ),
        migrations.AlterField(
            model_name='modultxn',
            name='salt',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Salt'),
        ),
    ]
