# Generated by Django 3.1.12 on 2021-07-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выслано'),
        ),
    ]
