# Generated by Django 3.1.5 on 2021-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_streamer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platronpayment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='order',
            name='card_pan',
            field=models.TextField(null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_code',
            field=models.IntegerField(null=True, verbose_name='Код ошибки'),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_desc',
            field=models.TextField(null=True, verbose_name='Описание ошибки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_system',
            field=models.TextField(null=True, verbose_name='Платежная система'),
        ),
    ]
