# Generated by Django 3.1.5 on 2021-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210209_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('price',), 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='api.CartItem', verbose_name='Билеты'),
        ),
    ]
