# Generated by Django 3.1.12 on 2022-02-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210804_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulTxn',
            fields=[
                ('testing', models.PositiveSmallIntegerField(choices=[(0, 'Prod'), (1, 'Test')], verbose_name='Testing')),
                ('pan_mask', models.CharField(max_length=32, verbose_name='Pan mask')),
                ('unix_timestamp', models.IntegerField(verbose_name='Unix timestamp')),
                ('salt', models.CharField(max_length=32, verbose_name='Salt')),
                ('rrn', models.BigIntegerField(verbose_name='RRN')),
                ('transaction_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Tx Id')),
                ('auth_number', models.BigIntegerField(verbose_name='Auth number')),
                ('auth_code', models.IntegerField(verbose_name='Auth code')),
                ('signature', models.CharField(max_length=64, verbose_name='Signature')),
                ('client_phone', models.CharField(max_length=32, verbose_name='Client phone')),
                ('client_email', models.CharField(max_length=64, verbose_name='Client email')),
                ('payment_method', models.CharField(max_length=64, verbose_name='Payment Method')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'ModulTxn',
                'verbose_name_plural': 'ModulTxns',
            },
        ),
        migrations.AlterField(
            model_name='placetimetable',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='api.place', verbose_name='Место'),
        ),
    ]
