# Generated by Django 3.1.12 on 2022-01-28 04:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210804_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(default=1, verbose_name='Категория')),
                ('ordering_number', models.IntegerField(default=100, verbose_name='№ П/П')),
                ('question', models.CharField(max_length=255, null=True, unique=True, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('category', 'ordering_number'),
            },
        ),
        migrations.CreateModel(
            name='FaqParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_number', models.IntegerField(default=100, verbose_name='№ П/П')),
                ('icon', models.ImageField(null=True, upload_to='icons/', verbose_name='Иконка')),
                ('expanded', models.BooleanField(default=False, verbose_name='Раскрыто по умолчанию')),
                ('question', models.CharField(max_length=255, null=True, unique=True, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Стать участником',
                'verbose_name_plural': 'Стать участником',
                'ordering': ('ordering_number',),
            },
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='HowTo',
        ),
        migrations.AlterField(
            model_name='placetimetable',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='api.place', verbose_name='Место'),
        ),
    ]
