# Generated by Django 3.1.10 on 2021-06-09 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210512_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='streamer',
        ),
        migrations.AddField(
            model_name='activity',
            name='streamers',
            field=models.ManyToManyField(to='api.Streamer', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Both')], default=3, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.TextField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='pageHeader',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_img/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_img/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='uniqUrl',
            field=models.TextField(default=uuid.uuid4, editable=False, verbose_name='Хеш для ссылки (/profile/)'),
        ),
    ]
