# Generated by Django 3.1.5 on 2021-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210212_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='t_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
