# Generated by Django 3.1.5 on 2021-06-06 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210512_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checkin_count',
            field=models.SmallIntegerField(default=0, verbose_name='Успешных попыток прохода'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_checkin',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последнего входа'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='uniqUrl',
            field=models.TextField(default=uuid.uuid4, editable=False, verbose_name='Хеш для ссылки (/profile/)'),
        ),
    ]
