# Generated by Django 3.1.12 on 2022-02-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220205_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatronPayment',
        ),
    ]
