# Generated by Django 3.1.5 on 2021-06-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210606_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='last_checkin',
            new_name='checkin_last',
        ),
    ]
