# Generated by Django 3.1.10 on 2021-06-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210609_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('priority', 'start'), 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Номер ПП'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='streamers',
            field=models.ManyToManyField(to='api.Streamer', verbose_name='Участник'),
        ),
    ]
