# Generated by Django 3.1.5 on 2021-02-13 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cartitem_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='ticket_qr/', verbose_name='QR')),
                ('streamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.streamer', verbose_name='От кого')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ticket', verbose_name='Билет')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tickets', models.ManyToManyField(blank=True, to='api.OrderItem', verbose_name='Билеты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
