# Generated by Django 3.1.5 on 2021-06-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210606_0055'),
        ('api', '0005_auto_20210610_0052'),
        ('api', '0004_auto_20210614_1145'),
    ]

    operations = [
    ]
