# Generated by Django 3.1.5 on 2021-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='o_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
