# Generated by Django 3.1.5 on 2021-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderitem_o_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
