# Generated by Django 3.1.5 on 2021-02-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_streamer_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название сети')),
                ('icon', models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Иконка соц. сети',
                'verbose_name_plural': 'Иконки соц. сетей',
            },
        ),
        migrations.AlterField(
            model_name='streamer',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='pageHeader',
            field=models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='photo',
            field=models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Аватар'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.socialicon', verbose_name='Иконка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.streamer', verbose_name='Стример')),
            ],
        ),
    ]
