# Generated by Django 3.1.5 on 2021-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210219_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='is_open_by_default',
            field=models.BooleanField(default=False, verbose_name='ЭТА ШТУКА ОТКРЫТА ПО УМОЛЧАНИЮ?;))'),
        ),
    ]
