# Generated by Django 3.1.5 on 2021-02-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_howto_is_open_by_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='linkIN',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='linkTW',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='linkVK',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='linkYT',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='views',
        ),
    ]
