# Generated by Django 3.1.5 on 2021-02-21 16:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210219_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howto',
            options={'ordering': ('order_number',), 'verbose_name': 'Как стать участником', 'verbose_name_plural': 'Как стать участником'},
        ),
        migrations.AlterField(
            model_name='howto',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ответ'),
        ),
    ]
