# Generated by Django 3.1.6 on 2021-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210214_2328'),
        ('api', '0012_auto_20210221_1908'),
    ]

    operations = [
    ]
