# Generated by Django 3.1.6 on 2021-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20210227_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Отображать?'),
        ),
    ]
