# Generated by Django 3.1.5 on 2021-03-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210227_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatronPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('payment_id', models.CharField(editable=False, max_length=32, unique=True, verbose_name='PaymentId')),
                ('redirect_url', models.CharField(editable=False, max_length=255, unique=True, verbose_name='RedirectURL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_tickets', to='api.streamer', verbose_name='От кого'),
        ),
    ]
