# Generated by Django 3.1.6 on 2021-03-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210227_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('id',)},
        ),
    ]
