# Generated by Django 3.1.6 on 2021-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210317_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='sells',
            field=models.BooleanField(default=True, verbose_name='Отображать блок билетов и подпись?'),
        ),
    ]
