# Generated by Django 3.1.5 on 2021-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210311_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platronpayment',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='platronpayment',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='PaymentId'),
        ),
    ]
