# Generated by Django 3.1.5 on 2021-03-11 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210311_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tickets',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='ticket',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_payed',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_one_day',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_two_day',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.tickettype', verbose_name='Билет'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='days_qty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1, verbose_name='На сколько дней?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.streamer', verbose_name='От кого'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.orderitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
