# Generated by Django 3.1.6 on 2021-03-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
    ]
