# Generated by Django 3.1.5 on 2021-03-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210312_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='u_id',
            new_name='id',
        ),
    ]
