# Generated by Django 3.1.5 on 2021-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210312_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='when_cleared',
            field=models.DateTimeField(null=True, verbose_name='Дата и время погашения'),
        ),
    ]
